name: Feature request
description: Suggest an improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What limitation are you facing?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should be added or changed?
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Expected impact
      description: Why this is valuable?
